### ISSUE TITLE
[Meta] Upstream changes

### ISSUE THREAD

**Issue by lukewarlow** [w3c/trusted-types#476]
This issue will track PRs to upstream changes to other specs.

**Comment by lukewarlow** [comment]
https://github.com/w3c/ServiceWorker/pull/1709 - Upstream https://w3c.github.io/trusted-types/dist/spec/#sw-integration

**Comment by lukewarlow** [comment]
HTML Sections to upstream:

- [ ] https://w3c.github.io/trusted-types/dist/spec/#extensions-to-the-windoworworkerglobalscope-interface - Not upstreaming as I don't think it's the norm to.
- [x] https://w3c.github.io/trusted-types/dist/spec/#enforcement-in-document-interface
- [x] https://w3c.github.io/trusted-types/dist/spec/#enforcement-in-domparser-interface
- [x] https://w3c.github.io/trusted-types/dist/spec/#enforcement-in-element-shadowroot-interfaces
- [x] https://w3c.github.io/trusted-types/dist/spec/#html-workers

- [-] https://w3c.github.io/trusted-types/dist/spec/#enforcement-in-sinks - Only HTMLIframeElement srcdoc upstreamed
- [ ] https://w3c.github.io/trusted-types/dist/spec/#enforcement-in-scripts - Still WIP so not upstreaming yet
- [ ] https://w3c.github.io/trusted-types/dist/spec/#enforcement-in-timer-functions - Still WIP so not upstreaming yet
- [ ] https://w3c.github.io/trusted-types/dist/spec/#enforcement-in-event-handler-content-attributes - Still WIP so not upstreaming yet
- [ ] https://w3c.github.io/trusted-types/dist/spec/#html-validate-the-string-in-context - Will be upstreamed as a separate PR
